version: "3"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: modbus-tcp-ingress
      MODULE_TYPE: INGRESS
      SERVER_HOST_ADDRESS: 127.0.0.1
      SERVER_HOST_PORT: 12345
      FUNCTION: holding_registers
      START_ADDRESS: 0
      LENGTH: 1
      INTERVAL_PERIOD: 5
      INTERVAL_UNIT: s
      OUTPUT_LABEL: registers
      EGRESS_URL: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
      HANDLER_PORT: 80
    ports:
      - 5000:80
